name: micasense
channels:
  - conda-forge
dependencies:
  - python=3.6
  - opencv=4.1
  - numpy
  - jupyter
  - matplotlib
  - pysolar
  - gdal
  - scikit-image
  - pytest
  - git
  - git-lfs
  - pandas
  - imageio
  - nb_conda
  - requests
  - packaging
  - pip
  - pytest-xdist
  - pip:
    - pyzbar
    - mapboxgl
    - pyexiftool<=0.4.13
    - jenkspy
    - rawpy
